#app
server:
    port: 8060


#spring
spring:
  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: users
    redis:
      hostName: localhost
      password: ehu100
      port: 6379
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1

# DRUID MYSQL DATABASE CONFIG
druid:
  url: jdbc:mysql://localhost:3306/demon?useUnicode=true&characterEncoding=utf-8&useSSL=false
  driver-class: com.mysql.jdbc.Driver
  username: root
  password: root
  initial-size: 1
  min-idle: 1
  max-active: 20
  test-on-borrow: true

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: me.yummykang.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #logic-delete-value: 0
    #logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#logging
logging:
  level:
   me.yummykang: trace
   org.springframework:
         data: DEBUG
         security: DEBUG

# JWT
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: "auth"
      refresh: refresh
      register: "auth/register"

